##########################################################################
# Copyright (C) 2021 Sangfor Ltd. All rights reserved.
# File Name   : Makefile
# Author      : bhyou
# mail        : bhyou@foxmail.com
# Created Time: Thu 24 Jun 2021 03:12:36 PM CST
#########################################################################

include ../makefile.defs

comOpt   += -override_timescale=1ps/1ps
macroOpt += +define+Tdelay=200

top      = top_tb
wavefile = vpd

useList  = 0
filename = class_method.sv

#filelist = flist.rtl
