##########################################################################
# Copyright (C) 2021 Sangfor Ltd. All rights reserved.
# File Name   : Makefile
# Author      : bhyou
# mail        : bhyou@foxmail.com
# Created Time: Thu 24 Jun 2021 03:12:36 PM CST
#########################################################################

include ../makefile.defs

 
comOpt   += -override_timescale=1ns/1ps
macroOpt += +define+Tdelay=200

top      = task_demo
wavefile = vpd

useList  = 0
filename = task_demo.sv

#filelist = flist.rtl
